server:
  port: 8080
  servlet:
    context-path: /swd

spring:
  datasource:
    # 1. Đổi URL để trỏ về localhost, cổng 3306, và database tên 'b2'
    url: jdbc:mysql://localhost:3306/b2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # 2. Đổi username thành 'root' (là username mặc định của XAMPP)
    username: root
    # 3. Đổi password thành rỗng (là password mặc định của XAMPP)
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # 4. Đổi dialect để tương thích với MariaDB/MySQL 5.x của XAMPP
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  signerKey: "S41x2cyVH7vp5sYf5Cj8a+rm31KNLCpb3VskEicbdV3v6WojSmqErjAcEmJjYdYI"
  valid-duration: 12000 # in seconds
  refreshAble-duration: 120000 # in seconds